name: Deploy Medusa to ECS

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Build & Deploy to AWS ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t medusa-repo:latest .

      - name: Tag image for ECR
        run: |
          docker tag medusa-repo:latest ${{ secrets.ECR_REGISTRY }}/medusa-repo:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/medusa-repo:latest

      - name: Deploy to ECS (Force new deployment)
        run: |
          aws ecs update-service \
            --cluster medusa-cluster \
            --service medusa-service \
            --force-new-deployment
